### PR TITLE
Change createThreadWithParams API from size_t to versioned struct

### PR DESCRIPTION
**Pull request by sirknightj**
*Issue #, if available:*
- N/A

*What was changed?*
- Change the new createThreadWithParams API introduced in #264 to a use versioned struct instead of just a single size_t parameter, thanks to suggestion of @MushMal.
- Remove designated initializers and use the older style of setting the values of the struct to 0 due to this error:
```log
D:\a\amazon-kinesis-video-streams-pic\amazon-kinesis-video-streams-pic\tst\utils\Thread.cpp(179): error C7555: use of designated initializers requires at least '/std:c++20'
```
- Adjust existing unit tests and add new unit tests for this changed behavior.
- New error code has been added: STATUS_INVALID_THREAD_PARAMS_VERSION
- Add a message if neither the KVS_DEFAULT_STACK_SIZE or CONSTRAINED_DEVICE is set.

*Why was it changed?*
- To allow for greater flexibility of modifying the new API in the future when more parameters are added, like thread name, priority, etc.

*How was it changed?*
- The API definition was adjusted. As this feature is not released yet, it does not break backwards compatibility. It would if the feature is released.
- Note that the Thread.c has ifdef for windows and non-windows, so everything is repeated twice.
- Note that we can extract the validation logic to a different function. We can move it and discuss where to keep it in a future PR.

*What testing was done for the changes?*
- Adjust existing unit tests to use changed API behavior.
- Add additional unit tests to check for the newly-added behavior.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by unicornss — APPROVED** [review]

File: src/utils/include/com/amazonaws/kinesis/video/utils/Include.h [hunk 1]
```diff
@@ -69,6 +69,7 @@ extern "C" {
 #define STATUS_EXPONENTIAL_BACKOFF_RETRIES_EXHAUSTED STATUS_UTILS_BASE + 0x0000002b
 #define STATUS_THREADPOOL_MAX_COUNT                  STATUS_UTILS_BASE + 0x0000002c
 #define STATUS_THREADPOOL_INTERNAL_ERROR             STATUS_UTILS_BASE + 0x0000002d
+#define STATUS_UTILS_INVALID_THREAD_PARAMS_VERSION   STATUS_UTILS_BASE + 0x0000002e
```
Comment (stefankiesz) [inline src/utils/include/com/amazonaws/kinesis/video/utils/Include.h:72]: (nit) no need to include "UTILS" in name.

File: tst/utils/Thread.cpp [hunk 2]
```diff
@@ -174,16 +180,29 @@ TEST_F(ThreadFunctionalityTest, NegativeTest)
...
+    EXPECT_NE(STATUS_SUCCESS, THREAD_CREATE_WITH_PARAMS(&threadId, &threadParams, emptyRoutine, NULL));
     EXPECT_EQ(0, threadId);
 
     // No out value case
-    EXPECT_NE(STATUS_SUCCESS, THREAD_CREATE(NULL, testThreadRoutine, NULL));
+    EXPECT_NE(STATUS_SUCCESS, THREAD_CREATE(NULL, emptyRoutine, NULL));
+
+    // Invalid version
+    threadParams.version = THREAD_PARAMS_CURRENT_VERSION + 100;
+    EXPECT_NE(STATUS_SUCCESS, THREAD_CREATE_WITH_PARAMS(&threadId, &threadParams, emptyRoutine, NULL));
```
Comment (stefankiesz) [inline tst/utils/Thread.cpp:200]: For as many of these failing test cases as possible, rather than checking for !SUCCESS, please check for the expected error code (so will be using EXPECT_EQ rather than EXPECT_NE).

**Review by stefankiesz — CHANGES_REQUESTED** [review]
Awesome

File: src/utils/include/com/amazonaws/kinesis/video/utils/Include.h (hunk 1 above)
Comment (sirknightj) [reply src/utils/include/com/amazonaws/kinesis/video/utils/Include.h:72]: Was mulling over that one.. I referenced the "tags" implementation and its status codes all had it. I'll remove it since  there's only 1 instance of this anyway.

File: tst/utils/Thread.cpp (hunk 2 above)
Comment (sirknightj) [reply tst/utils/Thread.cpp:200]: I made it NE SUCCESS for consistency. I can adjust it for this file for this PR. We can look into adjusting this for the rest of the codebase in the future as this should help prevent regressions.

**Review by stefankiesz — APPROVED** [review]

File: tst/utils/Thread.cpp [hunk 3]
```diff
@@ -26,9 +26,10 @@ PVOID testThreadRoutine(PVOID arg)
 
     // Mark as visited
     st->threadVisited = TRUE;
+    UINT64 sleepTime = st->threadSleepTime;
```
Comment (sirknightj) [inline tst/utils/Thread.cpp:29]: Moved this into the guarded section because:

```
2024-11-09T05:39:36.6508953Z ==================
2024-11-09T05:39:36.6509339Z WARNING: ThreadSanitizer: data race (pid=3464)
2024-11-09T05:39:36.6510114Z   Write of size 8 at 0x7ffc74c07ea0 by main thread:
2024-11-09T05:39:36.6512135Z     #0 defaultCreateThreadWithParams /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/src/utils/src/Thread.c:210:16 (kvspic_test+0x3ea736) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6528552Z     #1 ThreadFunctionalityTest_ThreadCreateAndReleaseSimpleCheckWithStack_Test::TestBody() /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/tst/utils/Thread.cpp:146:9 (kvspic_test+0x32e13e) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6530810Z     #2 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (kvspic_test+0x44558a) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6532067Z     #3 <null> <null> (libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
2024-11-09T05:39:36.6532483Z 
2024-11-09T05:39:36.6532689Z   Previous read of size 4 at 0x7ffc74c07ea0 by thread T2752:
2024-11-09T05:39:36.6534085Z     #0 testThreadRoutine(void*) /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/tst/utils/Thread.cpp:31:28 (kvspic_test+0x32cebc) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6535127Z 
2024-11-09T05:39:36.6535238Z   As if synchronized via sleep:
2024-11-09T05:39:36.6535757Z     #0 usleep <null> (kvspic_test+0xd1d2a) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6538617Z     #1 defaultThreadSleep /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/src/utils/src/Thread.c:283:13 (kvspic_test+0x3ea93c) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6542904Z     #2 ThreadFunctionalityTest_ThreadCreateAndCancel_Test::TestBody() /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/tst/utils/Thread.cpp:106:5 (kvspic_test+0x32da4c) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6545845Z     #3 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (kvspic_test+0x44558a) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6547095Z     #4 <null> <null> (libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
2024-11-09T05:39:36.6547524Z 
2024-11-09T05:39:36.6547641Z   Location is stack of main thread.
2024-11-09T05:39:36.6547876Z 
2024-11-09T05:39:36.6548143Z   Location is global '??' at 0x7ffc74beb000 ([stack]+0x1cea0)
2024-11-09T05:39:36.6548460Z 
2024-11-09T05:39:36.6548662Z   Thread T2752 (tid=6243, finished) created by main thread at:
2024-11-09T05:39:36.6549329Z     #0 pthread_create <null> (kvspic_test+0xd478d) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6550946Z     #1 defaultCreateThreadWithParams /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/src/utils/src/Thread.c:194:14 (kvspic_test+0x3ea6fd) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6553202Z     #2 defaultCreateThread /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/src/utils/src/Thread.c:242:5 (kvspic_test+0x3ea84f) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6555542Z     #3 ThreadFunctionalityTest_ThreadCreateAndCancel_Test::TestBody() /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/tst/utils/Thread.cpp:96:9 (kvspic_test+0x32d7fc) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6557567Z     #4 void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) <null> (kvspic_test+0x44558a) (BuildId: baf5dc344c10bb4b6e35338f8c13871da51827f4)
2024-11-09T05:39:36.6558795Z     #5 <null> <null> (libc.so.6+0x29d8f) (BuildId: 490fef8403240c91833978d494d39e537409b92e)
2024-11-09T05:39:36.6559226Z 
2024-11-09T05:39:36.6560158Z SUMMARY: ThreadSanitizer: data race /home/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/src/utils/src/Thread.c:210:16 in defaultCreateThreadWithParams
2024-11-09T05:39:36.6561185Z ==================
2024-11-09T05:39:36.6864834Z ##[error]Process completed with exit code 66.
```

File: tst/utils/Thread.cpp [hunk 4]
```diff
@@ -183,13 +184,19 @@ TEST_F(ThreadFunctionalityTest, ThreadCreateWithParamsNegativeTest)
     ThreadParams threadParams;
     threadParams.version = 0;
     threadParams.stackSize = threadStack;
+    STATUS tooLargeStatus = STATUS_SUCCESS;
```
Comment (stefankiesz) [inline tst/utils/Thread.cpp:187]: (nit) Let's rename to something like "threadCreateStatus".

Comment (sirknightj) [reply tst/utils/Thread.cpp]: Done
